services:
  - type: web
    name: cmthakurclasses
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: PORT
        value: 3000
